language: perl

sudo: false

perl:
    - "5.18-shrplib"
    
addons:
    apt:
        packages:
            - velvet
            - velvet-example

install:
    - "cpanm --quiet --notest Bio::Perl"
    - "export PATH=$PWD:$PATH"
    - "export OMP_NUM_THREADS=4"

script:
    - "VelvetOptimiser.pl --help"
    - "VelvetOptimiser.pl --version"
    - "! VelvetOptimiser.pl --awesomeness"
    - "test/run_test.sh"
