language: perl

sudo: false

perl:
    - "5.14"
    
addons:
    apt:
        packages:
            - velvet

install:
    - "cpanm --quiet --notest Bio::Perl"
    - "export PATH=$PWD:$PATH"

script:
    - "VelvetOptimiser --help"
    - "VelvetOptimiser --version"
    - "! VelvetOptimiser --awesomeness"
    - "test/run_test.sh"
